version: "3.5"

networks:
  openstates-network:
      name: openstates-network

services:
  widgets:
    build:
      context: .
    # volumes:
    #   - .:/code
    environment:
      - DATABASE_URL=postgresql://openstates:openstates@db/openstatesorg
    ports:
      - "5000:80"
    networks:
      - openstates-network
