version: "3.5"

networks:
  openstates-network:
      name: openstates-network

services:
  widgets:
    build:
      context: .
    # volumes:
    #   - .:/code
    environment:
      - DATABASE_URL=postgresql://openstates:openstates@db/openstatesorg
      - SECRET_KEY=testing-locally-not-secret
      - OPENSTATES_API_KEY
      - MAPBOX_ACCESS_TOKEN
      - DEBUG
    ports:
      - "5000:80"
    networks:
      - openstates-network
